<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Steppe.CaravanExperiments</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Steppe.CaravanSimulation\Steppe.CaravanSimulation.csproj" />
  </ItemGroup>
</Project>
